- id: buildifier
  name: Bazel Buildifier
  description: Format bazel BUILD files.
  language: system
  entry: buildifier $(find . -type f \( -iname BUILD -or -iname BUILD.bazel -or -iname WORKSPACE \))
